### ISSUE TITLE
dto response record 사용해보기

### ISSUE THREAD

**Issue by hansol775** [dnd-side-project/dnd-9th-9-backend#36]
## 📌 Feature Issue

저는 java 14버전부터 제공되는 record를 활용해서 response를 만드는데요,

record를 사용하면 코드를 많이 줄일 수 있어요.

<img width="562" alt="스크린샷 2023-08-16 오후 9 13 19" src="https://github.com/dnd-side-project/dnd-9th-9-backend/assets/46973058/f6a2206d-bb2c-48d3-bc2a-99eb0f47eda0">

위 사진과 같이 사용하면 좋습니다.

## ETC
>

**Comment by Ju-yeop** [comment]
조언 감사합니다! record에 대해서 찾아보니 장점이 많은 것 같아요
그런데 저희 프로젝트가 자바 11을 사용하고 있어서 이번 프로젝트에서는 적용이 불가능할 것 같습니다🥲
이번에는 롬복으로 대체하고 다음 프로젝트에서 꼭 적용해보겠습니다! 감사합니다!!

**Comment by kaley0421** [comment]
오..!!! 이런게 있는지 몰랐어요..!!! 🫢
저도 기억해 뒀다가 다음 프로젝트에서 꼭 적용해 보도록 하겠습니다 🥲
좋은 정보 알려주셔서 감사합니다 :) !!
